### ISSUE TITLE
ModuleNotFoundError: No module named 'src.data.tfidf'

### ISSUE THREAD

**Issue by kwang2049** [rrmenon10/ADAPET#1]
+ config_file=config/RTE.json
+ is_parallel=False
+ python -m src.train -c config/RTE.json -p False
Traceback (most recent call last):
  File "/home/anaconda3/envs/adapet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/adapet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ADAPET/src/train.py", line 12, in <module>
    from src.data.Batcher import Batcher
  File "/home/ADAPET/src/data/Batcher.py", line 6, in <module>
    from src.data.DatasetReader import DatasetReader
  File "/home/ADAPET/src/data/DatasetReader.py", line 8, in <module>
    from src.data.WiCReader import WiCReader
  File "/home/ADAPET/src/data/WiCReader.py", line 11, in <module>
    from src.data.tfidf import inv_freq
ModuleNotFoundError: No module named 'src.data.tfidf'

It seems like missing some file?

**Comment by rrmenon10** [comment]
Hi,

Thanks for the catch! The module is not important to the running of ADAPET, so I have removed the line.
