### ISSUE TITLE
ReCoRD Evaluation Errors

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#10]
For ReCoRD training, I'm running into an error on [this line](https://github.com/rrmenon10/ADAPET/blob/master/src/eval/Scorer.py#L84) during the evaluation loop. It appears that the `_compute_f1` in the `Scorer` class requires the `config` object to have a `model` attribute, which appears to have been removed in the released code. What is the correct value for this config variable? Given that value, I think the fix is easy (just add the value to the [ReCoRD config](https://github.com/rrmenon10/ADAPET/blob/master/config/ReCoRD.json) and/or [Config.py](https://github.com/rrmenon10/ADAPET/blob/master/src/utils/Config.py)).

Also, it looks like the variable should be set to either `*regular*` or something else, but either setting gives me an error soon after in the code -- I've included the tracebacks at the bottom of this issue. I'm using a slightly modified version of the repo, so these downstream errors could be due to my changes, but if you encounter these errors, it would be helpful to have the fixes for these as well. Thanks so much!

Here is the full traceback for the original model config error I described:
```
Eval: 32it [00:16,  1.93it/s]                                                                                                                                      | 0/4 [00:00<?, ?it/s]
Train:   0%|                                                                                                                                                       | 0/4 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "src/train.py", line 151, in <module>
    train(config)
  File "src/train.py", line 111, in train
    dev_acc, dev_logits, eval_train_logits, preds = dev_eval(config, model, batcher, batch_idx, dict_avg_val)
  File "/home/ejp416/adapet/src/eval/eval_model.py", line 60, in dev_eval
    _, train_scores = train_scorer.get_score("train")
  File "/home/ejp416/adapet/src/eval/Scorer.py", line 237, in get_score
    round_tot_acc = self._compute_acc()
  File "/home/ejp416/adapet/src/eval/Scorer.py", line 84, in _compute_acc
    elif self.is_record and  "regular" in self.config.model.lower():
AttributeError: 'Config' object has no attribute 'model'
```

Here is the traceback when I set `config.model='regular'`:
```
Eval: 32it [00:16,  1.93it/s]                                                                                                                                      | 0/4 [00:00<?, ?it/s]
Train:   0%|                                                                                                                                                       | 0/4 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "src/train.py", line 151, in <module>
    train(config)
  File "src/train.py", line 111, in train
    dev_acc, dev_logits, eval_train_logits, preds = dev_eval(config, model, batcher, batch_idx, dict_avg_val)
  File "/home/ejp416/adapet/src/eval/eval_model.py", line 60, in dev_eval
    _, train_scores = train_scorer.get_score("train")
  File "/home/ejp416/adapet/src/eval/Scorer.py", line 237, in get_score
    round_tot_acc = self._compute_acc()
  File "/home/ejp416/adapet/src/eval/Scorer.py", line 92, in _compute_acc
    if lbl_logit > max_lbl_logit:
TypeError: '>' not supported between instances of 'list' and 'int'
```

Here is the traceback when I set `config.model=''`:
```
Eval: 32it [00:16,  1.93it/s]                                                                                                                                      | 0/4 [00:00<?, ?it/s]
Train:   0%|                                                                                                                                                       | 0/4 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "src/train.py", line 151, in <module>
    train(config)
  File "src/train.py", line 111, in train
    dev_acc, dev_logits, eval_train_logits, preds = dev_eval(config, model, batcher, batch_idx, dict_avg_val)
  File "/home/ejp416/adapet/src/eval/eval_model.py", line 62, in dev_eval
    train_logits = train_scorer.get_logits()
  File "/home/ejp416/adapet/src/eval/Scorer.py", line 251, in get_logits
    return np.concatenate(self.list_logits, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 19 and the array at index 1 has size 20
```

**Comment by rrmenon10** [comment]
Thanks for bringing up this bug in the code. We do not use the 'regular' option for the ADAPET model, so leaving it empty was the right choice. The second part of the error was actually an oversight in something we commented and forgot to convert to an if-statement. It should be working now with the changes.

**Comment by ethanjperez** [comment]
Great, thanks!
