### ISSUE TITLE
codes are very too slow than being usable, how to use larger batchsize 

### ISSUE THREAD

**Issue by jackfeinmann5** [rrmenon10/ADAPET#19]
Hi
I am trying with WSC for larger bacthsize, I am getting this error, this is very too slow and I appreciate any suggestions on how to make it work, thanks

```
/user/jack/libs/anaconda3/envs/adapet/lib/python3.7/site-packages/torch/nn/modules/loss.py:516: UserWarning: Using a target size (torch.Size([1, 256])) that is different to the input size (torch.Size([32, 256])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
Traceback (most recent call last):
  File "/user/jack/libs/anaconda3/envs/adapet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/user/jack/libs/anaconda3/envs/adapet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/remote/idiap.svm/user.active/jack/dev/internshipadapet/others/ADAPET/src/train.py", line 126, in <module>
    train(config)
  File "/remote/idiap.svm/user.active/jack/dev/internshipadapet/others/ADAPET/src/train.py", line 93, in train
    loss, dict_val_update = model(sup_batch)
  File "/user/jack/libs/anaconda3/envs/adapet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/remote/idiap.svm/user.active/jack/dev/internshipadapet/others/ADAPET/src/adapet.py", line 224, in forward
    tgt[:, None].repeat(1, max_seq_len).float())  # [bs, max_seq_len]
  File "/user/jack/libs/anaconda3/envs/adapet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/user/jack/libs/anaconda3/envs/adapet/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 516, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/user/jack/libs/anaconda3/envs/adapet/lib/python3.7/site-packages/torch/nn/functional.py", line 2372, in binary_cross_entropy
    "!= input nelement ({})".format(target.numel(), input.numel()))
ValueError: Target and input must have the same number of elements. target nelement (256) != input nelement (8192)

```

**Comment by rrmenon10** [comment]
Hi, the code does not support higher batch sizes for WSC because of the way the prompt and training are designed for this task. Regarding slowness, using batch size 1, we got this code to run in less than an hour on a 2080Ti. What kind of speeds are you getting?
