### ISSUE TITLE
ValueError: could not broadcast input array from shape (4,) into shape (1,)

### ISSUE THREAD

**Issue by MoritzLaurer** [rrmenon10/ADAPET#28]
Thanks for the very interesting paper and code. I'm trying to train adapet on custom data (in Google Colab). 
I've prepared the data in the format as indicated in the documentation. my task is a binary sentiment classification task "positive" vs. "negative".

```
!python cli.py --data_dir data/sentiment-news-econ \
               --pattern 'The quote: "[TEXT1]". The quote is overall [LBL]' \
               --dict_verbalizer '{"positive": "verbalizer_1", "negative": "verbalizer_2"}'
```

I get the following error: 

```
Traceback (most recent call last):
  File "cli.py", line 54, in <module>
    train(config)
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/train.py", line 93, in train
    loss, dict_val_update = model(sup_batch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 213, in forward
    pet_disc_loss = self.get_decoupled_label_loss(batch)
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 178, in get_decoupled_label_loss
    lbl_logits = self.get_single_logits(pet_mask_ids, mask_idx, list_lbl) # [bs, num_lbl]
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 70, in get_single_logits
    lbl_ids[i, :len(i_lbl_ids)] = i_lbl_ids
ValueError: could not broadcast input array from shape (4,) into shape (1,)
```

The error seems to come from the following part in the source code. Where the token IDs for the labels are retrieved. 
https://github.com/rrmenon10/ADAPET/blob/6d2bfef5405ca53112235021d9fb8b36f641be9d/src/adapet.py#L70

I couldn't figure out what it causing it though :/

**Comment by rrmenon10** [comment]
Hi @MoritzLaurer, I think this might have to do with your labels, "verbalizer_1" and "verbalizer_2", actually being tokenized by the ALBERT tokenizer into more than one token. You should be good to go if you set "max_num_lbl_tokens" in cli.py to 4 in this case. Let me know if this doesn't work out and perhaps I can test it out.

**Comment by MoritzLaurer** [comment]
Thanks @rrmenon10  for the quick response. 
My labels are actually not "verbalizer_1" and "verbalizer_2", but "positive" and "negative". So I imagine that the correct dict_verbalizer would be the following?

```
!python cli.py --data_dir data/sentiment-news-econ \
               --pattern 'The quote: "[TEXT1]". The quote is overall [LBL]' \
               --dict_verbalizer '{"lbl_1": "positive", "lbl_2": "negative"}'
```

I have tried this, but then I get the following error: 

```
Traceback (most recent call last):
  File "cli.py", line 54, in <module>
    train(config)
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/train.py", line 92, in train
    sup_batch = next(train_iter)
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/data/Batcher.py", line 99, in get_train_batch
    self._init_train()
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/data/Batcher.py", line 71, in _init_train
    train_data = self.dataset_reader.read_dataset("train")
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/data/DatasetReader.py", line 64, in read_dataset
    return np.asarray(self.dataset_reader.read_dataset(split, is_eval))
  File "/content/drive/MyDrive/Colab Notebooks/Few-shot-experiments/ADAPET/src/data/GenericReader.py", line 99, in read_dataset
    raise ValueError("Label %s not in dictionary verbalizer" % json_string["LBL"])
ValueError: Label negative not in dictionary verbalizer
```

I am 100% sure though that the string "negative" is in my jsonl file, see screenshot below: 

<img width="1435" alt="Screenshot 2022-02-17 at 09 09 06" src="https://user-images.githubusercontent.com/41862082/154432625-efee249e-ad7e-4155-8286-9e3192c33e76.png">

**Comment by MoritzLaurer** [comment]
Ah I think I just understood the flag    --dict_verbalizer '{"lbl_1": "verbalizer_1", "lbl_2": "verbalizer_2"}'
"lbl_1" refers to the label string/int in my jsonl data file and "verbalizer_1" refers to the verbalised string on the label?
In that case, my correct flag would be   --dict_verbalizer '{"positive": "positive", "negative": "negative"}'

But with this, I'm getting this error: 

```
Traceback (most recent call last):
  File "cli.py", line 54, in <module>
    train(config)
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/train.py", line 93, in train
    loss, dict_val_update = model(sup_batch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 213, in forward
    pet_disc_loss = self.get_decoupled_label_loss(batch)
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 178, in get_decoupled_label_loss
    lbl_logits = self.get_single_logits(pet_mask_ids, mask_idx, list_lbl) # [bs, num_lbl]
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 88, in get_single_logits
    mask_prob = mask_prob.reshape(bs, self.num_lbl, self.config.max_num_lbl_tok, self.config.max_num_lbl_tok)
RuntimeError: shape '[1, 2, 1, 1]' is invalid for input of size 20

```

**Comment by amith-ananthram** [comment]
@MoritzLaurer I'm running into the same issue -- did you by chance figure it out?

**Comment by MoritzLaurer** [comment]
Unfortunately no. let me know if you figure it out :)

**Comment by rrmenon10** [comment]
Hi @amith-ananthram @MoritzLaurer, I've pushed a bug fix for this. Let me know if you still have any issues. Thanks!

**Comment by amith-ananthram** [comment]
@rrmenon10 it seems to be working now, thank you so much for the quick fix :)

**Comment by amith-ananthram** [comment]
(and congrats on the very cool work!)

**Comment by MoritzLaurer** [comment]
Great, thank you very much @rrmenon10 !

**Comment by MoritzLaurer** [comment]
Just tried to run it again, but still getting the error. 
Btw: I'm testing on google colab and for installing I always first run this: 
```
!git clone https://github.com/rrmenon10/ADAPET
!cd ADAPET
!pip install -r ADAPET/requirements.txt
!pip install numpy --upgrade  # numpy version in requirements.txt does not seem to be correct anymore
```

I noticed that the numpy version in the requirements.txt didn't seem to be the correct one anymore. maybe there is an issue with the requirements.txt? If I don't upgrade numpy as above, I get the message: "RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd" when running the '!python cli.py' command in colab (but the code continues running after printing the error message, but then produces again the error below).


And with or without upgrading numpy, I still get the previous error message: 
```
Traceback (most recent call last):
  File "cli.py", line 54, in <module>
    train(config)
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/train.py", line 93, in train
    loss, dict_val_update = model(sup_batch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 213, in forward
    pet_disc_loss = self.get_decoupled_label_loss(batch)
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 178, in get_decoupled_label_loss
    lbl_logits = self.get_single_logits(pet_mask_ids, mask_idx, list_lbl) # [bs, num_lbl]
  File "/content/drive/My Drive/Colab Notebooks/Few-shot-experiments/ADAPET/src/adapet.py", line 88, in get_single_logits
    mask_prob = mask_prob.reshape(bs, self.num_lbl, self.config.max_num_lbl_tok, self.config.max_num_lbl_tok)
RuntimeError: shape '[1, 2, 1, 1]' is invalid for input of size 20
```

**Comment by rrmenon10** [comment]
Hey @MoritzLaurer, could you confirm that [this line](https://github.com/rrmenon10/ADAPET/blob/baf2c8740e0e7c6e67175b8c8b30866855e3df67/src/data/GenericReader.py#L72) has max_num_lbl_tok in your version of the code? Thanks!

On numpy: I will check this out and make the change if necessary.

**Comment by MoritzLaurer** [comment]
ah no, my line 72 is 
`        return self.config.max_num_lbl` (without _tok)
I'll try manually deleting the cloned directory and reinstalling, maybe that fixes it

---update: 
after manually deleting and reinstalling on my google drive, it seems to be working now, thank you!
