### ISSUE TITLE
Tokens in `pet_logits` longer than `max_seq_len`

### ISSUE THREAD

**Issue by czarrar** [rrmenon10/ADAPET#33]
Hi,

Thanks for sharing the code for ADAPET!

I got the following error:

```
Traceback (most recent call last):
  File "cli.py", line 54, in <module>
    train(config)
  File "/home/ec2-user/SageMaker/ADAPET/src/train.py", line 93, in train
    loss, dict_val_update = model(sup_batch)
  File "/home/ec2-user/SageMaker/ADAPET/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/SageMaker/ADAPET/src/adapet.py", line 213, in forward
    pet_disc_loss = self.get_decoupled_label_loss(batch)
  File "/home/ec2-user/SageMaker/ADAPET/src/adapet.py", line 178, in get_decoupled_label_loss
    lbl_logits = self.get_single_logits(pet_mask_ids, mask_idx, list_lbl) # [bs, num_lbl]
  File "/home/ec2-user/SageMaker/ADAPET/src/adapet.py", line 79, in get_single_logits
    pet_mask_logits = torch.matmul(mask_idx_emb[:, :, None, :], pet_logits[:, None, :, :]).squeeze(
RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:549
```
In investigating this further, `pet_mask_ids` and later `pet_logits` have a size of [1,319] which is greater than the max sequence length of 256. One thing that I've tried is to keep only those indices in `pet_mask_ids` (within the `get_decoupled_label_loss` function) up to the max sequence length. Would that be an appropriate solution? Thanks!

**Comment by czarrar** [comment]
I realized that it would make more sense for me to limit the lengths of my TEXT1 and TEXT2 myself to ensure the total length of the pattern is kept within the maximum text length.
