### ISSUE TITLE
AttributeError: 'RTEReader' object has no attribute 'set_stop_words_ids'

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#4]
When I run `sh bin/train.sh config/RTE.json`, I receive the following error:
`AttributeError: 'RTEReader' object has no attribute 'set_stop_words_ids'`

What is the correct way to fix this issue? Should [RTEReader.__init__()](https://github.com/rrmenon10/ADAPET/blob/8d49eb0954ea6b70708f6ab22fe0018149890519/src/data/RTEReader.py#L17) initialize a `self.set_stop_words_ids` field, and if so, to what value?

Below is the full trace:
```
> sh bin/train.sh config/RTE.json
+ config_file=config/RTE.json
+ is_parallel=False
+ python -m src.train -c config/RTE.json
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 710/710 [00:00<00:00, 1.33MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 760k/760k [00:00<00:00, 17.2MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1.31M/1.31M [00:00<00:00, 25.9MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 893M/893M [00:19<00:00, 46.0MB/s]
Traceback (most recent call last):
  File "/home/ejp416/miniconda3/envs/adapet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ejp416/miniconda3/envs/adapet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ejp416/adapet/src/train.py", line 126, in <module>
    train(config)
  File "/home/ejp416/adapet/src/train.py", line 93, in train
    loss, dict_val_update = model(sup_batch)
  File "/home/ejp416/miniconda3/envs/adapet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ejp416/adapet/src/adapet.py", line 218, in forward
    self.get_pattern()))
  File "/home/ejp416/adapet/src/data/DatasetReader.py", line 73, in prepare_batch
    return self.dataset_reader.prepare_pet_mlm_batch(batch, mode=type.replace("PET_MLM_", ""))
  File "/home/ejp416/adapet/src/data/RTEReader.py", line 163, in prepare_pet_mlm_batch
    orig_input_ids, masked_input_ids, mask_idx = tokenize_pet_mlm_txt(self.tokenizer, self.config, txt_split_tuple[0], txt_split_tuple[1], txt_split_tuple[2], txt_trim, self.set_stop_words_ids)
AttributeError: 'RTEReader' object has no attribute 'set_stop_words_ids'
```

Thanks for your help!

**Comment by rrmenon10** [comment]
Hi,

Thanks for bringing up this issue. The stop_word_ids are not necessary for the repo and so I've removed it from the file. Try pulling the most recent commit.

**Comment by ethanjperez** [comment]
Great, thanks!
